CHBHTH/Controllers/UserController.cs
using CHBHTH.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CHBHTH.Controllers
{
    public class UserController : Controller
    {
        QLbanhang db = new QLbanhang();

        public ActionResult Dangky()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Dangky(TaiKhoan taiKhoan)
        {
            try
            {
                Session["userReg"] = taiKhoan;

                if (ModelState.IsValid)
                {
                    var check = db.TaiKhoans.FirstOrDefault(s => s.Email == taiKhoan.Email);
                    if (check == null)
                    {
                        ViewBag.RegOk = "Registered successfully. Sign in now";
                        ViewBag.isReg = true;
                        db.TaiKhoans.Add(taiKhoan);
                        db.SaveChanges();
                        return View("Dangky");
                    }
                    else
                    {
                        ViewBag.RegOk = "Email already exists! Please choose another email.";
                        return View("Dangky");
                    }

                }
                return View("Dangky");
            }
            catch
            {
                return View();
            }
        }

        [AllowAnonymous]
        public ActionResult Dangnhap()
        {
            return View();

        }

        [HttpPost]
        public ActionResult Dangnhap(FormCollection userlog)
        {
            string userMail = userlog["userMail"].ToString();
            string password = userlog["password"].ToString();
            var islogin = db.TaiKhoans.FirstOrDefault(x => x.Email.Equals(userMail) && x.Matkhau.Equals(password));

            if (islogin != null)
            {
                if (userMail == "taicq21@uef.edu.vn")
                {
                    Session["use"] = islogin;
                    return RedirectToAction("Index", "Admin/Home");
                }
                else
                {
                    Session["use"] = islogin;
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ViewBag.Fail = "Account or password is incorrect.";
                return View("Dangnhap");
            }
        }

        public ActionResult DangXuat()
        {
            Session["use"] = null;
            return RedirectToAction("Index", "Home");

        }

        public ActionResult Profile(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDQuyen = new SelectList(db.PhanQuyens, "IDQuyen", "TenQuyen", taiKhoan.IDQuyen);
            return View(taiKhoan);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNguoiDung,HoTen,Email,Dienthoai,Matkhau,IDQuyen,Diachi")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taiKhoan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Profile", new { id = taiKhoan.MaNguoiDung });

            }
            ViewBag.IDQuyen = new SelectList(db.PhanQuyens, "IDQuyen", "TenQuyen", taiKhoan.IDQuyen);
            return View(taiKhoan);
        }
        public static byte[] encryptData(string data)
        {
            System.Security.Cryptography.MD5CryptoServiceProvider md5Hasher = new System.Security.Cryptography.MD5CryptoServiceProvider();
            byte[] hashedBytes;
            System.Text.UTF8Encoding encoder = new System.Text.UTF8Encoding();
            hashedBytes = md5Hasher.ComputeHash(encoder.GetBytes(data));
            return hashedBytes;
        }
        public static string md5(string data)
        {
            return BitConverter.ToString(encryptData(data)).Replace("-", "").ToLower();
        }
    }
}

CHBHTH/Controllers/danhmucController.cs
using CHBHTH.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CHBHTH.Controllers
{
    public class danhmucController : Controller
    {
        QLbanhang db = new QLbanhang();
        public ActionResult danhmucpartial()
        {
            var danhmuc = db.LoaiHangs.Where(n => n.TenLoai != "A").Take(6).ToList();
            return PartialView(danhmuc);
        }

    }
}

CHBHTH/Controllers/sanphamController.cs
using CHBHTH.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace CHBHTH.Controllers
{
    public class sanphamController : Controller
    {
        private QLbanhang db = new QLbanhang();
        public ActionResult Index()
        {
            var sanPhams = db.SanPhams.Include(s => s.LoaiHang).Include(s => s.NhaCungCap);
            return View(sanPhams.ToList());
        }

        public ActionResult suapartial()
        {
            var ip = db.SanPhams.Where(n => n.MaLoai == 1).Take(4).ToList();
            return PartialView(ip);
        }

        public ActionResult raupartial()
        {
            var ip = db.SanPhams.Where(n => n.MaLoai == 2).Take(4).ToList();
            return PartialView(ip);
        }

        public ActionResult dauanpartial()  
        {
            var ip = db.SanPhams.Where(n => n.MaLoai == 3).Take(4).ToList();
            return PartialView(ip);
        }

        public ActionResult xemchitiet(int Masp = 0)
        {
            var chitiet = db.SanPhams.SingleOrDefault(n => n.MaSP == Masp);
            if (chitiet == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(chitiet);
        }

        public ActionResult xemchitietdanhmuc(int MaLoai)
        {
            var ip = db.SanPhams.Where(n => n.MaLoai == MaLoai).ToList();
            return PartialView(ip);

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CHBHTH/Views/Shared/_LayoutClient.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        <link href="/Home/css/styles.css" rel="stylesheet" />
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="~/css/styles.css" rel="stylesheet" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

    </head>
    <body>
        @{ var u = Session["use"] as CHBHTH.Models.TaiKhoan; }
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
            <div class="container">
                @Html.ActionLink("GYMGEAR", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"> </span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mx-0 mx-lg-1"> @Html.ActionLink("About Us", "About", "Home", new { area = "" }, new { @class = "nav-link py-3 px-0 px-lg-3 rounded" }) </li>
                        <li class="nav-item mx-0 mx-lg-1 dropdown">@Html.ActionLink("Product", "index", "sanpham", new { area = "" }, new { @class = "nav-link py-3 px-0 px-lg-3 rounded" }) </li>
                    </ul>

                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mx-0 mx-lg-1">  @Html.Action("GioHangPartial", "GioHang", new { @class = "giohang" }) </li>
                    </ul>

                    <ul class="navbar-nav ms-auto ">
                        @{ if (u != null)
                            {
                                <li class="nav-item mx-0 mx-lg-1">
                                    <a style="color:white" href="@Url.Action("Profile", "User", new { id = u.MaNguoiDung  })"> Hi: @u.Email</a>
                                    <br />
                                    <a style="color:red" href="/User/DangXuat"> Log Out</a>
                                </li>

                            }
                            else
                            {
                                <td class="nav-item mx-0 mx-lg-1"> @Html.ActionLink("Login", "Dangnhap", "User", new { area = "" }, new { @class = "nav-link py-3 px-0 px-lg-3 rounded" }) </td>

                            } }
                    </ul>
                </div>
          </div>
                </nav>
                <div class="container body-content">
                    @RenderBody()
                    <hr />
                </div>

                @Scripts.Render("~/bundles/jquery")
                @Scripts.Render("~/bundles/bootstrap")
                @RenderSection("scripts", required: false)
            </body>

            <!-- Footer-->
    <footer class="text-bg-success" style="padding-left:50px">
        <div class="row">
            <div class="col-md-4 col-sm-6">
                <h3>GYMGEAR INTRODUCTION</h3>
                <span>Company Introduction</span>
                <br />
                <span>Shop System</span>
                <br />
                <span>Employment Information</span>
            </div>
            <div class="col-md-4 col-sm-6">
                <h3>CUSTOMER SUPPORT</h3>
                <span>Payment Guide</span>
                <br />
                <span>Customer Policy</span>
                <br />
                <span>Return and Refund Policy</span>
            </div>
            <div class="col-md-4 col-sm-6">
                <h3>Let Us Help You</h3>
                <span>Blogs</span>
                <br />
                <span>Contact: 0123456789</span>
                <br />
                <span>Email: Gymgear@gmail.com</span>
            </div>
        </div>
        <hr />
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright &copy; 2024 GYMGEAR. All rights reserved. </small></div>
        </div>
    </footer>

            <script src="~/Content/ckeditor/ckfinder/ckfinder.js"></script>

            <script src="~/Content/ckeditor/ckeditor.js"></script>

            <script src="~/Content/ckeditor/adapters/jquery.js"></script>
            <script>
            </script>

            @RenderSection("DoanJS", false)
 </html>

CHBHTH/Views/Shared/_LayoutClient2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/css/styles.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
    <body>
        @{ var u = Session["use"] as CHBHTH.Models.TaiKhoan; }
        <nav class="navbar navbar-expand-lg navbar-light text-bg-light">
            <div class="container px-4 px-lg-5">
                @Html.ActionLink("GYMGEAR", "Index", "Home", new { area = "" }, new { @class = "navbar-brand " , style = "color: red; font-weight: bold; text-decoration: underline;" })       
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"> @Html.ActionLink("Home Page", "Index", "Home", new { area = "" }, new { @class = "nav-link activ", style = "font-weight: bold;" })</li>
                        <li class="nav-item"> @Html.ActionLink("About Us", "About", "Home", new { area = "" }, new { @class = "nav-link activ", style = "font-weight: bold;" })</li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" style = "font-weight: bold; id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Product Portfolio </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li> @Html.ActionLink("Product Portfolio", "index", "sanpham", new { area = "" }, new { @class = "dropdown-item", style = "font-weight: bold;" }) </li>

                                <li><hr class="dropdown-divider" /></li>
                                <li> @Html.Action("danhmucpartial", "danhmuc", new { @class = "dropdown-item", style = "font-weight: bold;" }) </li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <button class="btn btn-outline-secondary" type="submit">
                            @Html.Action("GioHangPartial", "GioHang", new { @class = "giohang" })
                        </button>
                        <ul class="navbar-nav ms-auto ">
                            @{ if (u != null)
                                {
                                    <li class="nav-item mx-0 mx-lg-1">
                                        <a style="color:black" href="@Url.Action("Profile", "User", new { id = u.MaNguoiDung  })"> @u.Email</a>
                                        <br />
                                        <a style="color:red" href="/User/DangXuat"> Log out</a>
                                    </li>
                                }
                                else
                                {
                                    <td class="nav-item mx-0 mx-lg-1"> @Html.ActionLink("Login", "Dangnhap", "User", new { area = "" }, new { @class = "nav-link py-3 px-0 px-lg-3 rounded", style = "font-weight: bold;" }) </td>

                                } }
                        </ul>
                    </form>
                </div>
            </div>
        </nav>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

        @RenderBody()
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>

    <footer class="text-bg-success" style="padding-left:50px; background-color: blue;">
        <div class="row">
            <div class="col-md-4 col-sm-6">
                <h3>GYMGEAR Introduction</h3>
                <span>Company Introduction</span>
                <br />
                <span>Shop System</span>
                <br />
                <span>Employment Information</span>
            </div>
            <div class="col-md-4 col-sm-6">
                <h3>Customer Support</h3>
                <span>Payment Guide</span>
                <br />
                <span>Customer Policy</span>
                <br />
                <span>Return and Refund Policy</span>
            </div>
            <div class="col-md-4 col-sm-6">
                <h3>Let Us Help You</h3>
                <span>Blogs</span>
                <br />
                <span>Contact: 0123456789</span>
                <br />
                <span>Email: Gymgear@gmail.com</span>
            </div>
        </div>
        <hr />
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright &copy; 2024 GYMGEAR. All rights reserved. </small></div>
        </div>
    </footer>
    <script src="~/Content/js/scripts.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/Content/ckeditor/ckfinder/ckfinder.js"></script>

    <script src="~/Content/ckeditor/ckeditor.js"></script>

    <script src="~/Content/ckeditor/adapters/jquery.js"></script>


    <script>
    </script>

    @RenderSection("DoanJS", false)
</html>